/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9-dev at Wed Jun 21 17:43:47 2017. */

#include "command.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t vss_command_Robot_Command_fields[4] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, vss_command_Robot_Command, id, id, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, vss_command_Robot_Command, left_vel, id, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, vss_command_Robot_Command, right_vel, left_vel, 0),
    PB_LAST_FIELD
};

const pb_field_t vss_command_Global_Commands_fields[6] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, vss_command_Global_Commands, id, id, 0),
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , OTHER, vss_command_Global_Commands, is_team_yellow, id, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, vss_command_Global_Commands, robot_commands, is_team_yellow, &vss_command_Robot_Command_fields),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, vss_command_Global_Commands, situation, robot_commands, 0),
    PB_FIELD(  5, STRING  , OPTIONAL, CALLBACK, OTHER, vss_command_Global_Commands, name, situation, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
