/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9-dev at Wed Jun 21 17:43:52 2017. */

#include "debug.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t vss_debug_Pose_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, vss_debug_Pose, id, id, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, vss_debug_Pose, x, id, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, vss_debug_Pose, y, x, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, vss_debug_Pose, yaw, y, 0),
    PB_LAST_FIELD
};

const pb_field_t vss_debug_Path_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, vss_debug_Path, id, id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, vss_debug_Path, poses, id, &vss_debug_Pose_fields),
    PB_LAST_FIELD
};

const pb_field_t vss_debug_Global_Debug_fields[4] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, vss_debug_Global_Debug, step_poses, step_poses, &vss_debug_Pose_fields),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, vss_debug_Global_Debug, final_poses, step_poses, &vss_debug_Pose_fields),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, vss_debug_Global_Debug, paths, final_poses, &vss_debug_Path_fields),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
