/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9-dev at Wed Jun 21 17:43:52 2017. */

#ifndef PB_VSS_DEBUG_DEBUG_PB_H_INCLUDED
#define PB_VSS_DEBUG_DEBUG_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _vss_debug_Global_Debug {
    pb_callback_t step_poses;
    pb_callback_t final_poses;
    pb_callback_t paths;
/* @@protoc_insertion_point(struct:vss_debug_Global_Debug) */
} vss_debug_Global_Debug;

typedef struct _vss_debug_Path {
    uint32_t id;
    pb_callback_t poses;
/* @@protoc_insertion_point(struct:vss_debug_Path) */
} vss_debug_Path;

typedef struct _vss_debug_Pose {
    uint32_t id;
    float x;
    float y;
    bool has_yaw;
    float yaw;
/* @@protoc_insertion_point(struct:vss_debug_Pose) */
} vss_debug_Pose;

/* Default values for struct fields */

/* Initializer values for message structs */
#define vss_debug_Pose_init_default              {0, 0, 0, false, 0}
#define vss_debug_Path_init_default              {0, {{NULL}, NULL}}
#define vss_debug_Global_Debug_init_default      {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define vss_debug_Pose_init_zero                 {0, 0, 0, false, 0}
#define vss_debug_Path_init_zero                 {0, {{NULL}, NULL}}
#define vss_debug_Global_Debug_init_zero         {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define vss_debug_Global_Debug_step_poses_tag    1
#define vss_debug_Global_Debug_final_poses_tag   2
#define vss_debug_Global_Debug_paths_tag         3
#define vss_debug_Path_id_tag                    1
#define vss_debug_Path_poses_tag                 2
#define vss_debug_Pose_id_tag                    1
#define vss_debug_Pose_x_tag                     2
#define vss_debug_Pose_y_tag                     3
#define vss_debug_Pose_yaw_tag                   4

/* Struct field encoding specification for nanopb */
extern const pb_field_t vss_debug_Pose_fields[5];
extern const pb_field_t vss_debug_Path_fields[3];
extern const pb_field_t vss_debug_Global_Debug_fields[4];

/* Maximum encoded size of messages (where known) */
#define vss_debug_Pose_size                      21
/* vss_debug_Path_size depends on runtime parameters */
/* vss_debug_Global_Debug_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define DEBUG_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
