/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9-dev at Wed Jun 21 17:43:37 2017. */

#ifndef PB_VSS_STATE_STATE_PB_H_INCLUDED
#define PB_VSS_STATE_STATE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _vss_state_Global_State {
    bool has_id;
    uint32_t id;
    bool has_origin;
    bool origin;
    pb_callback_t balls;
    pb_callback_t robots_yellow;
    pb_callback_t robots_blue;
    bool has_situation;
    uint32_t situation;
    bool has_time;
    uint32_t time;
    bool has_goals_yellow;
    uint32_t goals_yellow;
    bool has_goals_blue;
    uint32_t goals_blue;
    pb_callback_t name_yellow;
    pb_callback_t name_blue;
/* @@protoc_insertion_point(struct:vss_state_Global_State) */
} vss_state_Global_State;

typedef struct _vss_state_Pose {
    float x;
    float y;
    bool has_yaw;
    float yaw;
/* @@protoc_insertion_point(struct:vss_state_Pose) */
} vss_state_Pose;

typedef struct _vss_state_RGB {
    uint32_t r;
    uint32_t g;
    uint32_t b;
/* @@protoc_insertion_point(struct:vss_state_RGB) */
} vss_state_RGB;

typedef struct _vss_state_Ball_State {
    vss_state_Pose pose;
    bool has_v_pose;
    vss_state_Pose v_pose;
    bool has_k_pose;
    vss_state_Pose k_pose;
    bool has_k_v_pose;
    vss_state_Pose k_v_pose;
/* @@protoc_insertion_point(struct:vss_state_Ball_State) */
} vss_state_Ball_State;

typedef struct _vss_state_Robot_State {
    vss_state_Pose pose;
    bool has_v_pose;
    vss_state_Pose v_pose;
    bool has_k_pose;
    vss_state_Pose k_pose;
    bool has_k_v_pose;
    vss_state_Pose k_v_pose;
    bool has_color;
    vss_state_RGB color;
/* @@protoc_insertion_point(struct:vss_state_Robot_State) */
} vss_state_Robot_State;

/* Default values for struct fields */

/* Initializer values for message structs */
#define vss_state_RGB_init_default               {0, 0, 0}
#define vss_state_Pose_init_default              {0, 0, false, 0}
#define vss_state_Ball_State_init_default        {vss_state_Pose_init_default, false, vss_state_Pose_init_default, false, vss_state_Pose_init_default, false, vss_state_Pose_init_default}
#define vss_state_Robot_State_init_default       {vss_state_Pose_init_default, false, vss_state_Pose_init_default, false, vss_state_Pose_init_default, false, vss_state_Pose_init_default, false, vss_state_RGB_init_default}
#define vss_state_Global_State_init_default      {false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define vss_state_RGB_init_zero                  {0, 0, 0}
#define vss_state_Pose_init_zero                 {0, 0, false, 0}
#define vss_state_Ball_State_init_zero           {vss_state_Pose_init_zero, false, vss_state_Pose_init_zero, false, vss_state_Pose_init_zero, false, vss_state_Pose_init_zero}
#define vss_state_Robot_State_init_zero          {vss_state_Pose_init_zero, false, vss_state_Pose_init_zero, false, vss_state_Pose_init_zero, false, vss_state_Pose_init_zero, false, vss_state_RGB_init_zero}
#define vss_state_Global_State_init_zero         {false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define vss_state_Global_State_id_tag            1
#define vss_state_Global_State_origin_tag        2
#define vss_state_Global_State_balls_tag         3
#define vss_state_Global_State_robots_yellow_tag 4
#define vss_state_Global_State_robots_blue_tag   5
#define vss_state_Global_State_situation_tag     6
#define vss_state_Global_State_time_tag          7
#define vss_state_Global_State_goals_yellow_tag  8
#define vss_state_Global_State_goals_blue_tag    9
#define vss_state_Global_State_name_yellow_tag   10
#define vss_state_Global_State_name_blue_tag     11
#define vss_state_Pose_x_tag                     1
#define vss_state_Pose_y_tag                     2
#define vss_state_Pose_yaw_tag                   3
#define vss_state_RGB_r_tag                      1
#define vss_state_RGB_g_tag                      2
#define vss_state_RGB_b_tag                      3
#define vss_state_Ball_State_pose_tag            1
#define vss_state_Ball_State_v_pose_tag          2
#define vss_state_Ball_State_k_pose_tag          3
#define vss_state_Ball_State_k_v_pose_tag        4
#define vss_state_Robot_State_pose_tag           1
#define vss_state_Robot_State_v_pose_tag         2
#define vss_state_Robot_State_k_pose_tag         3
#define vss_state_Robot_State_k_v_pose_tag       4
#define vss_state_Robot_State_color_tag          5

/* Struct field encoding specification for nanopb */
extern const pb_field_t vss_state_RGB_fields[4];
extern const pb_field_t vss_state_Pose_fields[4];
extern const pb_field_t vss_state_Ball_State_fields[5];
extern const pb_field_t vss_state_Robot_State_fields[6];
extern const pb_field_t vss_state_Global_State_fields[12];

/* Maximum encoded size of messages (where known) */
#define vss_state_RGB_size                       18
#define vss_state_Pose_size                      15
#define vss_state_Ball_State_size                68
#define vss_state_Robot_State_size               88
/* vss_state_Global_State_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define STATE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
