/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9-dev at Wed Jun 21 17:43:37 2017. */

#include "state.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t vss_state_RGB_fields[4] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, vss_state_RGB, r, r, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, vss_state_RGB, g, r, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, vss_state_RGB, b, g, 0),
    PB_LAST_FIELD
};

const pb_field_t vss_state_Pose_fields[4] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, vss_state_Pose, x, x, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, vss_state_Pose, y, x, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, vss_state_Pose, yaw, y, 0),
    PB_LAST_FIELD
};

const pb_field_t vss_state_Ball_State_fields[5] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, vss_state_Ball_State, pose, pose, &vss_state_Pose_fields),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, vss_state_Ball_State, v_pose, pose, &vss_state_Pose_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, vss_state_Ball_State, k_pose, v_pose, &vss_state_Pose_fields),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, vss_state_Ball_State, k_v_pose, k_pose, &vss_state_Pose_fields),
    PB_LAST_FIELD
};

const pb_field_t vss_state_Robot_State_fields[6] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, vss_state_Robot_State, pose, pose, &vss_state_Pose_fields),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, vss_state_Robot_State, v_pose, pose, &vss_state_Pose_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, vss_state_Robot_State, k_pose, v_pose, &vss_state_Pose_fields),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, vss_state_Robot_State, k_v_pose, k_pose, &vss_state_Pose_fields),
    PB_FIELD(  5, MESSAGE , OPTIONAL, STATIC  , OTHER, vss_state_Robot_State, color, k_v_pose, &vss_state_RGB_fields),
    PB_LAST_FIELD
};

const pb_field_t vss_state_Global_State_fields[12] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, vss_state_Global_State, id, id, 0),
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , OTHER, vss_state_Global_State, origin, id, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, vss_state_Global_State, balls, origin, &vss_state_Ball_State_fields),
    PB_FIELD(  4, MESSAGE , REPEATED, CALLBACK, OTHER, vss_state_Global_State, robots_yellow, balls, &vss_state_Robot_State_fields),
    PB_FIELD(  5, MESSAGE , REPEATED, CALLBACK, OTHER, vss_state_Global_State, robots_blue, robots_yellow, &vss_state_Robot_State_fields),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, vss_state_Global_State, situation, robots_blue, 0),
    PB_FIELD(  7, UINT32  , OPTIONAL, STATIC  , OTHER, vss_state_Global_State, time, situation, 0),
    PB_FIELD(  8, UINT32  , OPTIONAL, STATIC  , OTHER, vss_state_Global_State, goals_yellow, time, 0),
    PB_FIELD(  9, UINT32  , OPTIONAL, STATIC  , OTHER, vss_state_Global_State, goals_blue, goals_yellow, 0),
    PB_FIELD( 10, STRING  , OPTIONAL, CALLBACK, OTHER, vss_state_Global_State, name_yellow, goals_blue, 0),
    PB_FIELD( 11, STRING  , OPTIONAL, CALLBACK, OTHER, vss_state_Global_State, name_blue, name_yellow, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(vss_state_Ball_State, pose) < 65536 && pb_membersize(vss_state_Ball_State, v_pose) < 65536 && pb_membersize(vss_state_Ball_State, k_pose) < 65536 && pb_membersize(vss_state_Ball_State, k_v_pose) < 65536 && pb_membersize(vss_state_Robot_State, pose) < 65536 && pb_membersize(vss_state_Robot_State, v_pose) < 65536 && pb_membersize(vss_state_Robot_State, k_pose) < 65536 && pb_membersize(vss_state_Robot_State, k_v_pose) < 65536 && pb_membersize(vss_state_Robot_State, color) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_vss_state_RGB_vss_state_Pose_vss_state_Ball_State_vss_state_Robot_State_vss_state_Global_State)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(vss_state_Ball_State, pose) < 256 && pb_membersize(vss_state_Ball_State, v_pose) < 256 && pb_membersize(vss_state_Ball_State, k_pose) < 256 && pb_membersize(vss_state_Ball_State, k_v_pose) < 256 && pb_membersize(vss_state_Robot_State, pose) < 256 && pb_membersize(vss_state_Robot_State, v_pose) < 256 && pb_membersize(vss_state_Robot_State, k_pose) < 256 && pb_membersize(vss_state_Robot_State, k_v_pose) < 256 && pb_membersize(vss_state_Robot_State, color) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_vss_state_RGB_vss_state_Pose_vss_state_Ball_State_vss_state_Robot_State_vss_state_Global_State)
#endif


/* @@protoc_insertion_point(eof) */
